Sure, here's the contents for the file `/sensemap/config/camera_params.yaml`:

camera:
  type: RGB-D
  resolution:
    width: 640
    height: 480
  fps: 30
  intrinsic:
    fx: 525.0
    fy: 525.0
    cx: 319.5
    cy: 239.5
  distortion:
    k1: 0.1
    k2: -0.2
    p1: 0.0
    p2: 0.0
    k3: 0.0
  extrinsic:
    rotation:
      - [1.0, 0.0, 0.0]
      - [0.0, 1.0, 0.0]
      - [0.0, 0.0, 1.0]
    translation:
      - [0.0, 0.0, 0.0]